// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCszgGXFstUugV_uZ5IAgca7rRUIPNgmVA',
    appId: '1:98616239839:web:5f8c28c3d8c6504d01ab6a',
    messagingSenderId: '98616239839',
    projectId: 'promo-71442',
    authDomain: 'promo-71442.firebaseapp.com',
    storageBucket: 'promo-71442.firebasestorage.app',
    measurementId: 'G-C33ETR2GLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF8iagPOuCpQ4nT8cMwIWp1Sn_6dnBtmE',
    appId: '1:98616239839:android:d0366d747460ab5a01ab6a',
    messagingSenderId: '98616239839',
    projectId: 'promo-71442',
    storageBucket: 'promo-71442.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCyxct8r1bZO1fR1T7V2GuG3WGZUlU_eI',
    appId: '1:98616239839:ios:76ce113d4f31bc3501ab6a',
    messagingSenderId: '98616239839',
    projectId: 'promo-71442',
    storageBucket: 'promo-71442.firebasestorage.app',
    iosBundleId: 'com.promotions.promoz',
  );
}
